online_store/config/routes.rb
Rails.application.routes.draw do
  get 'purchases/index'
  put 'purchases/show'
  get 'purchaselist/index'
  get 'purchaselist/show'
  get 'users/index'
  put 'users/:id/remove' => 'users#remove'
  get 'users/show'
  get 'feedbacks/new'
  get 'feedbacks/show'
  get 'wishlist/index'
  get 'mainpage/index'
  get 'cart/add_purchase'
  put 'items/index'
  resources :items do
    member do
      put "addcart", to: "items#cart"
      put "removecart", to: "items#cart"
      put "addwish", to: "items#wishlist"
      put "removewish", to: "items#wishlist"
    end
  end
  resources :cart, only:[:index] do
    member do
      put "clearcart", to: "cart#clear_cart"
      put "buynow", to: "cart#buy_now"
    end
  end
  resources :wishlist, only:[:index]
  resources :mainpage, only:[:index]
  resources :feedbacks
  resources :users, except: :create
  resources :purchaselist, only:[:index,:show] do
    member do
      put "returnpurchase", to: "purchaselist#return_update"
      put "approverequest", to: "purchaselist#approve_request"
    end
  end
  resources :purchases
  post 'create_user' => 'users#create' ,as: :create_user


  devise_for :users, :path_prefix => 'my', controllers:{
      registrations: 'registrations',
      confirmations: 'confirmations' ,
      omniauth_callbacks: 'omniauth'
  }

  root to: 'mainpage#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

online_store/app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :thumbnail
  belongs_to :user
  has_many :carts
  has_many :added_items, through: :carts, source: :user
  has_many :user_purchases, through: :purchaselists, source: :purchase

  BRAND = %w{Apple Alphabet Bose Caterpillar Duke Epsilon Ford Gucci Hope Island Jockey Samsung}

  CATEGORY = %w{ Electronics Gaming Books Apparel Machinery Watches }

  TAX = %w{One Two Three}
end

online_store/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :cart, :wishlist]
  before_action :authenticate_user!, :except => [:show, :index]

  # GET /items
  # GET /items.json
  def index
    type = params[:type]
    field = params[:field]

    @items = Item.all.order("updated_at desc")
    if type == "sort"
      @items = Item.all.order("#{field} asc")
    end


  end

  # GET /items/1
  # GET /items/1.json
  def show
    if @item.purchase_count.nil?
      @item.update_column(:purchase_count, 0)
    end
    @item.update_column(:purchase_count, @item.purchase_count + 1)
  end

  # GET /items/new
  def new
    @item = current_user.items.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.build(item_params)
    authorize! :read,@item
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  # add/remove items from cart of current user
  def cart
    type = params[:type]

    if type == "addcart"
      #current_user.cart_additions << @item
      current_user.carts.create!(:item =>@item, :iscart? =>true)
      redirect_to cart_index_path, notice: "#{@item.name} was added to your cart"
    elsif type == "removecart"
      current_user.carts.update(:item =>@item, :iscart? =>false)
      #current_user.cart_additions.delete(@item)
      redirect_to root_path, notice: "#{@item.name} was removed from your cart"
    else
      redirect_to item_path(@item), notice: "Looks like nothing happened. Try again!"

    end
  end

  def wishlist
    type = params[:type]

    if type =="addwishlist"
      #current_user.cart_additions.iswishlist? = true
      current_user.carts.create!(:item =>@item, :iswishlist? =>true)
      redirect_to wishlist_index_path, notice: "#{@item.name} was added to your wishlist"
    elsif type == "removewish"
      current_user.carts.update(:item =>@item, :iswishlist? =>false)
      #current_user.cart_additions.delete(@item)
      redirect_to root_path, notice: "#{@item.name} was removed from your wishlist"
    else
      redirect_to item_path(@item), notice: "Looks like nothing happened. Try again!"
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:brand, :name, :category, :thumbnail, :is_restricted?, :is_age_restricted?, :quantity, :cost, :purchase_count, :user_id)
  end
end

online_store/app/helpers/items_helper.rb
module ItemsHelper

  def user_added_to_cart? user, item
    user.carts.where(user: user, item: item, iscart?: true).any?
  end

  def user_added_to_wish? user,item
    user.carts.where(user: user, item: item, iswishlist?: true).any?
  end


  def total_cost user
    @cart_list = user.carts.where(user: user, iscart?: true)
    @cart_items = Item.find(@cart_list.pluck(:item_id))

    total_price = 0
    @cart_items.each do |item|
      if item.tax_slab == "one"
        tax = 0.1
      elsif item.tax_slab == "two"
        tax = 0.15
      elsif item.tax_slab == "three"
        tax = 0.2
      else
        tax = 0.05
      end
      total_price = total_price + item.cost*(1 + tax)
    end

    #if user.age >= 65
    #total_price=total_price*0.9
    #end

    return total_price.round(2)
  end


  def total_cost_item item
    if item.tax_slab == "one"
      tax=0.1
    elsif item.tax_slab == "two"
      tax =0.15
    elsif item.tax_slab=="three"
      tax=0.2
    else
      tax=0.05

    end
    total_price=item.cost*(1+tax)
    return total_price.round(2)
  end

  def user_pending? user
    @purchases=user.purchases
    @purchases.each do |f|
      @purchase_lists=f.purchaselists
      @purchase_lists.each do |k|
        if k.ispending?
          return true
        end
      end
    end
    return false
  end

  def purchase_pending? purchase
    @purchase_lists=purchase.purchaselists
    @purchase_lists.each do |f|
        if f.ispending?
          return true
        end
    end
    return false
    end
end

online_store/app/views/items/_form.html.erb
<div class = "columns">
  <div class = "column is-12 is-centered">
    <%= simple_form_for(@item) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="field">
        <div class="control">
          <%= f.input :name, required: true, autofocus: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.input :cost, required: true, autofocus: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.input :quantity, required: true, autofocus: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
        </div>
      </div>

      <div class="columns">
        <div class="field column is-4">
          <div class="control">
            <label class ="label">Brand</label>
            <div class="control has-icons-left">
            <span class =  "select">
              <%= f.input_field :brand, collection: Item::BRAND, prompt: "Select Brand" %>
            </span>
              <span class = "icon is-small is-left">
              <i class = "fa fa-tag"></i>
            </span>
            </div>
          </div>
        </div>

        <div class="field column is-4">
          <div class="control">
            <label class="label">Category</label>
            <div class="control has-icons-left">
            <span class = "select">
              <%= f.input_field :category, collection: Item::CATEGORY, prompt: "Select Category"  %>
            </span>
              <span class = "icon is-small is-left">
              <i class = "fa fa-tag"></i>
            </span>
            </div>
          </div>
        </div>


        <div class="field column is-4">
          <div class="control">
            <label class = "label">Tax Slab</label>
            <div class = "control has-icons-left">
            <span class = "select">
              <%= f.input_field :tax_slab, collection: Item::TAX, prompt: "Select Tax Slab" %>
            </span>
              <span class = "icon is-small is-left">
              <i class = "fa fa-tag"></i>
            </span>
            </div>
          </div>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.input :is_restricted? %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.input :is_age_restricted? %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <div class="file">
            <label class="file-label">
              <%= f.input :thumbnail, as: :file, required: true, input_html: { class: "file-input" }, wrapper: false, label: false  %>
              <span class="file-cta">
              <span class="file-icon">
                <i class="fa fa-upload"></i>
              </span>
              <span class="file-label">
                Choose a thumbnail…
              </span>
            </span>
            </label>
          </div>
        </div>
      </div>
      <div class="form-actions">
        <%= f.button :submit, class:"button is-dark" %>
      </div>
    <% end %>

  </div>
</div>

online_store/app/views/items/_item-controls.html.erb
<% if user_signed_in? %>

  <% if user_added_to_cart?(current_user, item) %>

    <%= link_to 'Remove from Cart', removecart_item_path(item, type: "removecart"), method: :put, class: "button is-danger is-fullwidth" %>

    <% if controller.controller_name == "item" %>
      <%= link_to 'Buy Now', buynow_cart_path(item),method: :put, class:"button is-success is-fullwidth mt1" %>
    <% end %>
    <% elsif user_added_to_wish?(current_user, item) %>
    <%= link_to 'Remove from Wishlist', removewish_item_path(item, type: "removewish"), method: :put, class: "button is-danger is-fullwidth" %>

    <% if controller.controller_name == "item" %>
      <%= link_to 'Buy Now', buynow_cart_path(item),method: :put, class:"button is-success is-fullwidth mt1" %>
    <% end %>
  <% else %>
    <%= link_to 'Add to Cart', addcart_item_path(item, type: "addcart"), method: :put, class: "button is-link is-fullwidth" %>
    <%= link_to 'Add to Wish', addwish_item_path(item, type: "addwishlist"), method: :put, class: "button is-link is-fullwidth " %>
  <% end %>

<% else %>
  <%= link_to 'Register to Add', new_user_registration_path, class: "button is-link is-fullwidth" %>
<% end %>

online_store/app/views/items/_item.html.erb
<div class="book">
  <div class="card">
    <div class="card-image">
      <figure class="image is-3by4">
        <%= link_to image_tag(item.thumbnail), item if item.thumbnail.attached? %>
      </figure>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <p class="title is-4"><%= item.name %></p>
          <p class="subtitle is-6"><%= item.brand %></p>
          <p class="subtitle is-8">$<%= item.cost %></p>
          <p class="subtitle is-6">Availabilty:<%= item.quantity %> &nbsp Views:<%= item.purchase_count %></p>

        </div>
      </div>

      <div class="content">
        <% if user_signed_in? %>

          <% if item.quantity > 0 %>
          <% if user_added_to_wish?(current_user, item) %>

            <%= link_to ' Rm /Wishlist', removewish_item_path(item, type: "removewish"), method: :put, class: "button is-small is-danger is-link" %>
          <% else %>
            <%= link_to 'Add to Wislist', addwish_item_path(item, type: "addwishlist"), method: :put, class: "button is-small is-link " %>
          <% end %>

          <% if user_added_to_cart?(current_user, item)  %>
            <%= link_to 'Rm /Cart ', removecart_item_path(item, type: "removecart"), method: :put, class: "button is-small is-danger is-link" %>
          <% else %>
            <%= link_to 'Add to Cart', addcart_item_path(item, type: "addcart"), method: :put, class: "button is-small is-link " %>
          <% end %>

          <% if controller.controller_name == "items" %>
            <%= link_to 'Buy Now', buynow_cart_path(item),method: :put, class:"button is-success is-fullwidth mt1" %>
          <% end %>
            <%else %>
            <%= link_to 'Subscribe?', root_path, class:"button is-success is-fullwidth mt1" %>

        <% end %>

        <% else %>
          <%= link_to 'Register to Add', new_user_registration_path, class: "button is-link is-fullwidth" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="controls pt2">
    <%if user_signed_in? %>
      <% if can? :manage, @items %>
        <%= link_to 'Edit', edit_item_path(item), class:"button is-small is-rounded" %>
        <%= link_to 'Delete', item, method: :delete, data: { confirm: "Are you sure? "}, class:"button is-small is-rounded" %>
      <% end %>
    <%end %>
  </div>
</div>

online_store/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

online_store/app/views/items/index.html.erb
<div class="pageloader is-active">
<section class="hero">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <i class="fa fa-book"></i> Online Store
      </h1>
      <h2 class="subtitle">
        Check out the item collection
      </h2>
    </div>
  </div>
</section>

  <section class="section">
    <%= link_to ' Sort by cost', items_index_path(:type=>"sort", :field=>"cost") , method: :put, class: "button is-small is-danger is-link" %>
    <%= link_to ' Sort by popularity', items_index_path(:type=>"sort", :field=>"purchase_count"), method: :put, class: "button is-small is-danger is-link" %>
    <%= link_to ' Sort by Brand', items_index_path(:type=>"sort", :field=>"brand"), method: :put, class: "button is-small is-danger is-link" %>
    <%= link_to ' Sort by Name', items_index_path(:type=>"sort", :field=>"name"), method: :put, class: "button is-small is-danger is-link" %>
    <%= link_to ' Sort by availablity', items_index_path(:type=>"sort", :field=>"quantity"), method: :put, class: "button is-small is-danger is-link" %>

  </section>
<section class="section">
  <div class="item-grid">
    <%= render @items %>
  </div>
</section>
</div>

online_store/app/views/items/new.html.erb
<section class="section">
  <div class="columns is-centered">
    <div class="column is-6">
      <h1 class="title is-3">New Item</h1>
      <%= render 'form', item: @item %>
    </div>
  </div>
</section>

online_store/app/views/items/show.html.erb
<div class="section">
  <div class="columns">
    <div class="column is-4">
      <%= image_tag @item.thumbnail.variant(resize: "320x495"), alt: "#{@item.name} #{@item.brand}" %>
    </div>
    <div class="column">
      <h1 class="title is-2"><%= @item.name %><h1>

        <div class="content">
          <%= render 'item-controls', item: @item %>
          <p><strong>Category:</strong></p>
          <%= @item.category %>
        </div>

        <% #if admin? %>
        <%if user_signed_in? %>
          <%if can? :edit,@item %>
          <%= link_to 'Edit', edit_item_path(@item) %> |
        <% end %>
        <%end %>
    </div>
  </div>
</div>