online_store/config/routes.rb
Rails.application.routes.draw do
  get 'purchases/index'
  put 'purchases/show'
  get 'purchaselist/index'
  get 'purchaselist/show'
  get 'users/index'
  put 'users/:id/remove' => 'users#remove'
  get 'users/show'
  get 'feedbacks/new'
  get 'feedbacks/show'
  get 'wishlist/index'
  get 'mainpage/index'
  get 'cart/add_purchase'
  put 'items/index'
  resources :items do
    member do
      put "addcart", to: "items#cart"
      put "removecart", to: "items#cart"
      put "addwish", to: "items#wishlist"
      put "removewish", to: "items#wishlist"
    end
  end
  resources :cart, only:[:index] do
    member do
      put "clearcart", to: "cart#clear_cart"
      put "buynow", to: "cart#buy_now"
    end
  end
  resources :wishlist, only:[:index]
  resources :mainpage, only:[:index]
  resources :feedbacks
  resources :users, except: :create
  resources :purchaselist, only:[:index,:show] do
    member do
      put "returnpurchase", to: "purchaselist#return_update"
      put "approverequest", to: "purchaselist#approve_request"
    end
  end
  resources :purchases
  post 'create_user' => 'users#create' ,as: :create_user


  devise_for :users, :path_prefix => 'my', controllers:{
      registrations: 'registrations',
      confirmations: 'confirmations' ,
      omniauth_callbacks: 'omniauth'
  }

  root to: 'mainpage#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

online_store/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]  #:confirmable
  has_many :items, dependent: :destroy
  has_many :feedbacks
  has_many :purchases
  has_many :carts
  has_many :cart_additions, through: :carts, source: :item

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = provider_data.info.name
    end
  end

end

online_store/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully updated User."
      redirect_to root_path
    else
      render :action => 'edit'
    end
  end
  def new

  end
  def create
      @user = User.create!(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'A new user has been created. ' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @users=User.all
  end

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?

    if @user.update(user_params)
      flash[:notice] = "Successfully updated User."
      redirect_to root_path
    else
      render :action => 'edit'
    end
  end

  def remove
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully updated User."
      redirect_to root_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully updated User."
      redirect_to root_path
    else
      render :action => 'edit'
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :phone, :address, :age, :id, :password, :password_confirmation, :card_name, :card_no, :card_exp, :cvv)
  end
end

online_store/app/helpers/users_helper.rb
module UsersHelper
end

online_store/app/views/users/_table.html.erb
<table class="table is-striped is-fullwidth is-hoverable">
  <thead>
  <tr>
    <th><abbr title="Name">Name</abbr></th>
    <th>Email</th>
    <th><abbr title="Age">Age</abbr></th>
    <th><abbr title="Age">Status</abbr></th>
    <th><abbr title="Age">Actions</abbr></th>
  </tr>
  </thead>
  <tbody>
  <%@users.each do |f| %>
  <%if !f.isguest? %>
    <tr>
      <td><%=f.name %></td>
      <td><%=f.email %></td>
      <td><%=f.age %></td>
      <% if user_pending?(f)%>
        <td>Pending</td>
        <%else %>
        <td></td>
        <%end %>
      <td><%= link_to 'Purchase History', purchase_path(f), class: "button is-small is-link " %></td>
      <td><%= link_to 'Edit', edit_user_path(f), class: "button is-small is-link " %></td>
      <%if !f.isadmin?%>
      <td><%= link_to 'Delete', f,method: :delete, data: { confirm: "Are you sure? "}, class: "button is-small is-link " %></td>
        <%end %>
    </tr>
  <%end %>
    <%end %>
  </tbody>
</table>

online_store/app/views/users/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">

<h2 class="title is-2" >Edit <%@user.name %></h2>

        <%= simple_form_for(@user) do |f| %>
          <%= f.error_notification %>

  <div class="form-inputs">
    <div class="field">
      <div class="control">
    <%= f.input :name, required: false, autofocus: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }%>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :email, required: true, autofocus: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }%>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :age,
                    required: true,
                    autofocus: true,
                    input_html: { class:"input" }, wrapper: false, label_html: { class:"label" }%>
      </div>
    </div>

    <div class="form-inputs">
      <div class="field">
        <div class="control">
          <%= f.input :phone, required: false, autofocus: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }%>
        </div>
      </div>
      <div class="form-inputs">
        <div class="field">
          <div class="control">
            <%= f.input :address, required: false, autofocus: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }%>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= f.input :card_name,
                        required: true,
                        autofocus: true,
                        input_html: { class:"input" }, wrapper: false, label_html: { class:"label" }%>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= f.input :card_no,
                        required: true,
                        autofocus: true,
                        input_html: { class:"input" }, wrapper: false, label_html: { class:"label" }%>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= f.input :card_exp,
                        required: true,
                        autofocus: true,
                        input_html: { class:"input" }, wrapper: false, label_html: { class:"label" }%>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= f.input :cvv,
                        required: true,
                        autofocus: true,
                        input_html: { class:"input" }, wrapper: false, label_html: { class:"label" }%>
          </div>
        </div>

      </div>

  <div class="form-actions">
    <%= f.button :submit, "Update", class:"button is-warning" %>
  </div>
<% end %>

      </div>
    </div>
  </div>
    </div>
  </div>
</section>

online_store/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

online_store/app/views/users/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">

        <h2 class="title is-2" >Create User</h2>

        <%= simple_form_for(User.new,url: create_user_path) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">

            <div class="field">
              <div class="control">
                <%= f.input :name, required: true, autofocus: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" }%>
              </div>
            </div>
            <div class="field">
              <div class="control">
                <%= f.input :email, required: true, autofocus: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" }%>
              </div>
            </div>
            <div class="field">
              <div class="control">
                <%= f.input :age,
                            required: true,
                            autofocus: true,
                            input_html: { class:"input" }, wrapper: false, label_html: { class:"label" }%>
              </div>
            </div>

            <div class="field">
              <div class="control">
                <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length), input_html: { class:"input" }, wrapper: false, label_html: { class:"label" }%>
              </div>
            </div>
            <div class="field">
              <div class="control">
                <%= f.input :password_confirmation, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
              </div>
            </div>

            <div class="field">
              <div class="control">
                <%= f.input :phone, required: false, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
              </div>
            </div>

            <div class="field">
              <div class="control">
                <%= f.input :address, required: false , input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
              </div>
            </div>

            <div class="field">
              <div class="control">
                <%= f.input :card_name,
                            required: true,
                            autofocus: true,
                            input_html: { class:"input" }, wrapper: false, label_html: { class:"label" }%>
              </div>
            </div>

            <div class="field">
              <div class="control">
                <%= f.input :card_no,
                            required: true,
                            autofocus: true,
                            input_html: { class:"input" }, wrapper: false, label_html: { class:"label" }%>
              </div>
            </div>

            <div class="field">
              <div class="control">
                <%= f.input :card_exp,
                            required: true,
                            autofocus: true,
                            input_html: { class:"input" }, wrapper: false, label_html: { class:"label" }%>
              </div>
            </div>

            <div class="field">
              <div class="control">
                <%= f.input :cvv,
                            required: true,
                            autofocus: true,
                            input_html: { class:"input" }, wrapper: false, label_html: { class:"label" }%>
              </div>
            </div>


          </div>
          <br />
          <div class="form-actions">
            <div class="field">
              <div class="control">
                <%= f.button :submit, "Sign up", class:"button is-warning is-medium" %>
              </div>
        <% end %>

        </div>
        </div>
      </div>
    </div>
  </div>
</section>

online_store/app/views/users/show.html.erb
<section class="section">
  <div class="columns is-centered">
    <div class="column is-6">
      <h1 class="title is-3">Users</h1>
      <%= render 'table', book: @users %>
    </div>
    <%= link_to 'New User', new_user_path, class: "button is-small is-link " %>
  </div>
</section>