online_store/config/routes.rb
Rails.application.routes.draw do
  get 'purchases/index'
  put 'purchases/show'
  get 'purchaselist/index'
  get 'purchaselist/show'
  get 'users/index'
  put 'users/:id/remove' => 'users#remove'
  get 'users/show'
  get 'feedbacks/new'
  get 'feedbacks/show'
  get 'wishlist/index'
  get 'mainpage/index'
  get 'cart/add_purchase'
  put 'items/index'
  resources :items do
    member do
      put "addcart", to: "items#cart"
      put "removecart", to: "items#cart"
      put "addwish", to: "items#wishlist"
      put "removewish", to: "items#wishlist"
    end
  end
  resources :cart, only:[:index] do
    member do
      put "clearcart", to: "cart#clear_cart"
      put "buynow", to: "cart#buy_now"
    end
  end
  resources :wishlist, only:[:index]
  resources :mainpage, only:[:index]
  resources :feedbacks
  resources :users, except: :create
  resources :purchaselist, only:[:index,:show] do
    member do
      put "returnpurchase", to: "purchaselist#return_update"
      put "approverequest", to: "purchaselist#approve_request"
    end
  end
  resources :purchases
  post 'create_user' => 'users#create' ,as: :create_user


  devise_for :users, :path_prefix => 'my', controllers:{
      registrations: 'registrations',
      confirmations: 'confirmations' ,
      omniauth_callbacks: 'omniauth'
  }

  root to: 'mainpage#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

online_store/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.isadmin?
      can :manage,:all
    else
      can :create,Feedback
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

online_store/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

online_store/app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :item
  belongs_to :user

end

online_store/app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user, optional: true
end

online_store/app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :thumbnail
  belongs_to :user
  has_many :carts
  has_many :added_items, through: :carts, source: :user
  has_many :user_purchases, through: :purchaselists, source: :purchase

  BRAND = %w{Apple Alphabet Bose Caterpillar Duke Epsilon Ford Gucci Hope Island Jockey Samsung}

  CATEGORY = %w{ Electronics Gaming Books Apparel Machinery Watches }

  TAX = %w{One Two Three}
end

online_store/app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  has_many :purchaselists
  has_many :purchaseaddons, through: :purchaselists, source: :item
end

online_store/app/models/purchaselist.rb
class Purchaselist < ApplicationRecord
  belongs_to :item
  belongs_to :purchase
end

online_store/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]  #:confirmable
  has_many :items, dependent: :destroy
  has_many :feedbacks
  has_many :purchases
  has_many :carts
  has_many :cart_additions, through: :carts, source: :item

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = provider_data.info.name
    end
  end

end

online_store/app/controllers/cart_controller.rb
class CartController < ApplicationController
  include ItemsHelper
  before_action :authenticate_user!

  def index
    #@cart_items = current_user.cart_additions
    #@wish_list = current_user.carts.where( iswishlist?:true )
    @cart_list = current_user.carts.where(iscart?: true )
    #@wish_user=Cart.users.where(user: current_user, iswishlist?: true)
    #@wish_items=Item.find(@wish_list.pluck(:item_id))
    @cart_items = Item.find(@cart_list.pluck(:item_id))
  end

  def clear_cart
    current_user.carts.where(iscart?: true ).update(:iscart? => false)

    redirect_to cart_index_path, notice: " All items was cleared from your cart"
  end

  def add_purchase

    total_price = total_cost(current_user)
    @purchase= current_user.purchases.create!(:tax_cost =>total_price)

    @cart_list = current_user.carts.where(user: current_user, iscart?: true)
    @cart_items = Item.find(@cart_list.pluck(:item_id))

    @cart_items.each do |item|
      @purchase.purchaseaddons << item
      item.update(quantity: item.quantity - 1)
    end
    current_user.carts.where(iscart?: true ).update(:iscart? => false)
    PurchaseMailer.with(user: current_user,items: @cart_items).purchased_notification.deliver_now
    redirect_to root_path, notice: " Purchase was successful"
  end

  def buy_now
    @item=Item.find(item_id)
    total_price=total_cost_item(@item)
    @purchase=current_user.purchases.create!(:tax_cost =>total_price)
    @purchase.purchaseaddons << @item
    @item.update(quantity: @item.quantity - 1)
    PurchaseMailer.with(user: current_user,items: @item).purchased_notification.deliver_now
    redirect_to root_path, notice: " Purchase was successful"
  end
  def item_id
    params.require(:id)
  end
end

online_store/app/helpers/application_helper.rb
module ApplicationHelper

  def admin?
    user_signed_in? && current_user.admin?
  end
end

online_store/app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

online_store/app/helpers/items_helper.rb
module ItemsHelper

  def user_added_to_cart? user, item
    user.carts.where(user: user, item: item, iscart?: true).any?
  end

  def user_added_to_wish? user,item
    user.carts.where(user: user, item: item, iswishlist?: true).any?
  end


  def total_cost user
    @cart_list = user.carts.where(user: user, iscart?: true)
    @cart_items = Item.find(@cart_list.pluck(:item_id))

    total_price = 0
    @cart_items.each do |item|
      if item.tax_slab == "one"
        tax = 0.1
      elsif item.tax_slab == "two"
        tax = 0.15
      elsif item.tax_slab == "three"
        tax = 0.2
      else
        tax = 0.05
      end
      total_price = total_price + item.cost*(1 + tax)
    end

    #if user.age >= 65
    #total_price=total_price*0.9
    #end

    return total_price.round(2)
  end


  def total_cost_item item
    if item.tax_slab == "one"
      tax=0.1
    elsif item.tax_slab == "two"
      tax =0.15
    elsif item.tax_slab=="three"
      tax=0.2
    else
      tax=0.05

    end
    total_price=item.cost*(1+tax)
    return total_price.round(2)
  end

  def user_pending? user
    @purchases=user.purchases
    @purchases.each do |f|
      @purchase_lists=f.purchaselists
      @purchase_lists.each do |k|
        if k.ispending?
          return true
        end
      end
    end
    return false
  end

  def purchase_pending? purchase
    @purchase_lists=purchase.purchaselists
    @purchase_lists.each do |f|
        if f.ispending?
          return true
        end
    end
    return false
    end
end

online_store/app/helpers/main_helper.rb
module MainHelper
end

online_store/app/helpers/mainpage_helper.rb
module MainpageHelper
end

online_store/app/helpers/omniauth_helper.rb
module OmniauthHelper
end

online_store/app/helpers/purchaselist_helper.rb
module PurchaselistHelper
end

online_store/app/helpers/purchases_helper.rb
module PurchasesHelper
end

online_store/app/helpers/store_helper.rb
module StoreHelper
end

online_store/app/helpers/users_helper.rb
module UsersHelper
end

online_store/app/helpers/wishlist_helper.rb
module WishlistHelper
end

online_store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Online Store</title>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application' %>
</head>

<body class="<%= yield (:body_class) %>">
<% if flash[:notice] %>
  <div class="notification is-success global-notification">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="notification is-danger global-notification">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class:"navbar-item" do %>
      <h1 class="title is-5 has-text-white">Online Store</h1>
    <% end  %>
    <div class="navbar-burger burger" data-target="navbar">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbar" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <%unless user_signed_in? %>
          <%= link_to 'Guest', items_path, class: 'button is-dark' %>
        <% end %>
        <div class="field is-grouped">

          <div id="navbar" class="navbar-menu">
            <div class="navbar-end">
              <div class="navbar-item">
                <%if user_signed_in? %>
                  <%if can? :create,@items %>
                    <%= link_to 'New Item', new_item_path, class: 'button is-dark' %>
                  <% end %>
                <% end %>
                <div class="field is-grouped">

                  <!-- <%# if total_cart_items %>
            <%#= link_to cart_path(@cart), class:"navbar-item button is-warning" do %>
              <span class="icon is-small">
                <i class="fa fa-shopping-cart"></i>
              </span>
              <span>Cart
                <#%= cart_count_over_one %>
                </span>
            <%# end %>
          <%# end %> -->
                  <%= link_to 'Feedback', feedbacks_new_path, class: "navbar-item button is-dark" %>
                  <% if user_signed_in? %>
                    <%if current_user.isadmin? %>
                    <%= link_to 'Users', users_show_path, class: "navbar-item button is-dark"  %>

                      <%end %>
                    <%= link_to 'Purchases', purchase_path(current_user), class: "navbar-item button is-dark"  %>
                    <%= link_to 'Cart', cart_index_path, class: "navbar-item button is-dark" %>
                    <%= link_to 'Wishlist', wishlist_index_path, class: "navbar-item button is-dark" %>
                    <div class="navbar-item has-dropdown is-hoverable">
                      <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
                      <div class="navbar-dropdown is-right">
                        <%= link_to edit_user_registration_path, class:"navbar-item" do %>
                          <%= current_user.name %> &nbsp;<%if current_user.isadmin? %> <span class="tag is-warning">ADMIN</span><% end %>
                        <% end %>
                        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                      </div>
                    </div>
                  <% else %>

                    <%= link_to "Sign In", new_user_session_path, class:"navbar-item button is-dark" %>
                    <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button is-dark"%>

                  <% end %>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

<%= yield(:header) %>

<div class="container">

  <%= yield %>

</div>

</body>
</html>