online_store/config/routes.rb
Rails.application.routes.draw do
  get 'purchases/index'
  put 'purchases/show'
  get 'purchaselist/index'
  get 'purchaselist/show'
  get 'users/index'
  put 'users/:id/remove' => 'users#remove'
  get 'users/show'
  get 'feedbacks/new'
  get 'feedbacks/show'
  get 'wishlist/index'
  get 'mainpage/index'
  get 'cart/add_purchase'
  put 'items/index'
  resources :items do
    member do
      put "addcart", to: "items#cart"
      put "removecart", to: "items#cart"
      put "addwish", to: "items#wishlist"
      put "removewish", to: "items#wishlist"
    end
  end
  resources :cart, only:[:index] do
    member do
      put "clearcart", to: "cart#clear_cart"
      put "buynow", to: "cart#buy_now"
    end
  end
  resources :wishlist, only:[:index]
  resources :mainpage, only:[:index]
  resources :feedbacks
  resources :users, except: :create
  resources :purchaselist, only:[:index,:show] do
    member do
      put "returnpurchase", to: "purchaselist#return_update"
      put "approverequest", to: "purchaselist#approve_request"
    end
  end
  resources :purchases
  post 'create_user' => 'users#create' ,as: :create_user


  devise_for :users, :path_prefix => 'my', controllers:{
      registrations: 'registrations',
      confirmations: 'confirmations' ,
      omniauth_callbacks: 'omniauth'
  }

  root to: 'mainpage#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

online_store/app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
  end

  def show
    @purchases=User.find(user_params).purchases.all
  end

  def user_params
    params.require(:id)
  end
end

online_store/app/helpers/purchases_helper.rb
module PurchasesHelper
end

online_store/app/views/purchases/_table.html.erb
<table class="table is-striped is-fullwidth is-hoverable">
  <thead>
  <tr>
    <th><abbr title="Name">Purchase</abbr></th>
    <th>Total Cost</th>
    <th>Status</th>
  </tr>
  </thead>
  <tbody>
  <%@purchases.each.with_index do |f,index| %>
      <tr>
        <td><%= link_to "Purchase #{index}", purchaselist_path(f) %></td>
        <td>$ <%=f.tax_cost %></td>
        <%if purchase_pending?(f) %>
          <td>Pending</td>
          <%else %>
          <td></td>
          <%end %>
      </tr>
  <%end %>
  </tbody>
</table>

online_store/app/views/purchases/index.html.erb
<h1>Purchases#index</h1>
<p>Find me in app/views/purchases/index.html.erb</p>

online_store/app/views/purchases/show.html.erb
<% if @purchases.any? %>
<section class="section">
  <div class="columns is-centered">
    <div class="column is-6">
      <h1 class="title is-3">Users</h1>
      <%= render 'table', item: @purchases %>
    </div>
  </div>

  <% else %>
  <article class="message">
    <div class="message-body">Looks like no items have been bought yet. <% if !current_user.isadmin?%> <%= link_to 'Buy some', cart_index_path %> <%end%>.</div>
  </article>
  <% end %>
</section>